wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
ppo_epochs:
  desc: null
  value: 500
step_rollout:
  desc: null
  value: 128
update_epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
clip_epsilon:
  desc: null
  value: 0.2
n_dom_modes:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1755881507
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
